<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="10" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="InetBankingV4" duration-ms="80949" started-at="2021-08-21T10:56:10Z" finished-at="2021-08-21T10:57:31Z">
    <groups>
    </groups>
    <test name="BankingAppChromeTest" duration-ms="42656" started-at="2021-08-21T10:56:10Z" finished-at="2021-08-21T10:56:52Z">
      <class name="com.inetBankingV4.testCases.TC_LoginDDT_002">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@5e3a8624]" name="setUp" is-config="true" duration-ms="4082" started-at="2021-08-21T16:26:10Z" finished-at="2021-08-21T16:26:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@5e3a8624]" name="loginTest" duration-ms="10284" started-at="2021-08-21T16:26:15Z" data-provider="LoginData" finished-at="2021-08-21T16:26:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347851]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tUpeqUv]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@5e3a8624]" name="loginTest" duration-ms="5189" started-at="2021-08-21T16:26:26Z" data-provider="LoginData" finished-at="2021-08-21T16:26:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr140789]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AeUdYdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.inetBankingV4.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@5e3a8624]" name="loginTest" duration-ms="4874" started-at="2021-08-21T16:26:31Z" data-provider="LoginData" finished-at="2021-08-21T16:26:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr318762]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UmejUru]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.inetBankingV4.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@5e3a8624]" name="loginTest" duration-ms="9847" started-at="2021-08-21T16:26:36Z" data-provider="LoginData" finished-at="2021-08-21T16:26:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347851]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tUpeqUv]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@5e3a8624]" name="loginTest" duration-ms="5165" started-at="2021-08-21T16:26:46Z" data-provider="LoginData" finished-at="2021-08-21T16:26:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr412356]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AeUdYdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.inetBankingV4.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@5e3a8624]" name="tearDown" is-config="true" duration-ms="1135" started-at="2021-08-21T16:26:51Z" finished-at="2021-08-21T16:26:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.inetBankingV4.testCases.TC_LoginDDT_002 -->
    </test> <!-- BankingAppChromeTest -->
    <test name="BankingAppFirefoxTest" duration-ms="38008" started-at="2021-08-21T10:56:53Z" finished-at="2021-08-21T10:57:31Z">
      <class name="com.inetBankingV4.testCases.TC_LoginDDT_002">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@4dfa3a9d]" name="setUp" is-config="true" duration-ms="5299" started-at="2021-08-21T16:26:53Z" finished-at="2021-08-21T16:26:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@4dfa3a9d]" name="loginTest" duration-ms="8291" started-at="2021-08-21T16:26:58Z" data-provider="LoginData" finished-at="2021-08-21T16:27:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347851]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tUpeqUv]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@4dfa3a9d]" name="loginTest" duration-ms="4895" started-at="2021-08-21T16:27:06Z" data-provider="LoginData" finished-at="2021-08-21T16:27:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr140789]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AeUdYdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.inetBankingV4.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@4dfa3a9d]" name="loginTest" duration-ms="4618" started-at="2021-08-21T16:27:11Z" data-provider="LoginData" finished-at="2021-08-21T16:27:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr318762]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UmejUru]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.inetBankingV4.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@4dfa3a9d]" name="loginTest" duration-ms="8926" started-at="2021-08-21T16:27:16Z" data-provider="LoginData" finished-at="2021-08-21T16:27:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347851]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tUpeqUv]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@4dfa3a9d]" name="loginTest" duration-ms="4940" started-at="2021-08-21T16:27:25Z" data-provider="LoginData" finished-at="2021-08-21T16:27:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr412356]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AeUdYdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.inetBankingV4.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.inetBankingV4.testCases.TC_LoginDDT_002@4dfa3a9d]" name="tearDown" is-config="true" duration-ms="716" started-at="2021-08-21T16:27:30Z" finished-at="2021-08-21T16:27:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.inetBankingV4.testCases.TC_LoginDDT_002 -->
    </test> <!-- BankingAppFirefoxTest -->
  </suite> <!-- InetBankingV4 -->
</testng-results>
